version: "3.9"

services:
  backend-service:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5151:5151"
    volumes:
      - ./backend:/app
    restart: unless-stopped
    container_name: backend-service

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app
    restart: unless-stopped
    container_name: frontend-service
    depends_on:
      - backend-service
