"""add_video_task_usage_and_asset_models

Revision ID: 0f69a04efd96
Revises: 1818262c512f
Create Date: 2025-05-13 00:29:56.101384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f69a04efd96'
down_revision: Union[str, None] = '1818262c512f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_video_usage',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('period_identifier', sqlmodel.sql.sqltypes.AutoString(length=7), nullable=False),
    sa.Column('videos_created_this_period', sa.Integer(), nullable=False),
    sa.Column('period_start_date', sa.DateTime(), nullable=False),
    sa.Column('period_end_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_user_video_usage_user_id_user_account')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_video_usage')),
    sa.UniqueConstraint('user_id', 'period_identifier', name='uq_user_period')
    )
    op.create_index(op.f('ix_user_video_usage_id'), 'user_video_usage', ['id'], unique=False)
    op.create_index(op.f('ix_user_video_usage_user_id'), 'user_video_usage', ['user_id'], unique=False)
    op.create_table('video_generation_task',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('prompt_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', name='videogenerationtaskstatus'), nullable=False),
    sa.Column('progress_percentage', sa.Integer(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('celery_task_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.CheckConstraint('progress_percentage >= 0 AND progress_percentage <= 100', name=op.f('ck_video_generation_task_ck_video_task_progress_range')),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_video_generation_task_user_id_user_account')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_video_generation_task'))
    )
    op.create_index(op.f('ix_video_generation_task_celery_task_id'), 'video_generation_task', ['celery_task_id'], unique=False)
    op.create_index(op.f('ix_video_generation_task_id'), 'video_generation_task', ['id'], unique=False)
    op.create_index(op.f('ix_video_generation_task_status'), 'video_generation_task', ['status'], unique=False)
    op.create_index(op.f('ix_video_generation_task_user_id'), 'video_generation_task', ['user_id'], unique=False)
    op.create_table('generated_video',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('final_video_url', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('visibility', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['video_generation_task.id'], name=op.f('fk_generated_video_task_id_video_generation_task')),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_generated_video_user_id_user_account')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_generated_video'))
    )
    op.create_index(op.f('ix_generated_video_id'), 'generated_video', ['id'], unique=False)
    op.create_index(op.f('ix_generated_video_task_id'), 'generated_video', ['task_id'], unique=True)
    op.create_index(op.f('ix_generated_video_user_id'), 'generated_video', ['user_id'], unique=False)
    op.create_table('generated_video_asset',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('video_id', sa.Uuid(), nullable=False),
    sa.Column('asset_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('asset_url', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['generated_video.id'], name=op.f('fk_generated_video_asset_video_id_generated_video')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_generated_video_asset'))
    )
    op.create_index(op.f('ix_generated_video_asset_id'), 'generated_video_asset', ['id'], unique=False)
    op.create_index(op.f('ix_generated_video_asset_video_id'), 'generated_video_asset', ['video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generated_video_asset_video_id'), table_name='generated_video_asset')
    op.drop_index(op.f('ix_generated_video_asset_id'), table_name='generated_video_asset')
    op.drop_table('generated_video_asset')
    op.drop_index(op.f('ix_generated_video_user_id'), table_name='generated_video')
    op.drop_index(op.f('ix_generated_video_task_id'), table_name='generated_video')
    op.drop_index(op.f('ix_generated_video_id'), table_name='generated_video')
    op.drop_table('generated_video')
    op.drop_index(op.f('ix_video_generation_task_user_id'), table_name='video_generation_task')
    op.drop_index(op.f('ix_video_generation_task_status'), table_name='video_generation_task')
    op.drop_index(op.f('ix_video_generation_task_id'), table_name='video_generation_task')
    op.drop_index(op.f('ix_video_generation_task_celery_task_id'), table_name='video_generation_task')
    op.drop_table('video_generation_task')
    op.drop_index(op.f('ix_user_video_usage_user_id'), table_name='user_video_usage')
    op.drop_index(op.f('ix_user_video_usage_id'), table_name='user_video_usage')
    op.drop_table('user_video_usage')
    # ### end Alembic commands ###
