"""add_email_verification_columns

Revision ID: b32291c5ccb5
Revises: ca6c81fc6b6b
Create Date: 2025-05-12 15:46:06.272654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b32291c5ccb5'
down_revision: Union[str, None] = 'ca6c81fc6b6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('email_verification_token', sa.String(), nullable=True))
    op.add_column('user_account', sa.Column('email_verification_token_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('user_account', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user_account', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_user_account_email_verification_token'), 'user_account', ['email_verification_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_account_email_verification_token'), table_name='user_account')
    op.alter_column('user_account', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user_account', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_column('user_account', 'email_verification_token_expires_at')
    op.drop_column('user_account', 'email_verification_token')
    # ### end Alembic commands ###
